### ISSUE TITLE
PCB design discussion

### ISSUE THREAD

**Issue by tido-** [petit-miner/Blueberry-PI#1]
Allwinner V3s SoC features two CSI module. CSI0 is used for MIPI CSI-2 interface and CSI1 is used for parallel interface. This is not documented in datasheet but by test and guess.

Falls du das noch nicht gesehen hast, mehr dazu: https://www.spinics.net/lists/linux-media/msg128062.html

**Comment by petit-miner** [comment]
Ja das habe ich gesehen. Ich weiß nur noch nicht welche Kamera ich verwenden soll, bzw. welche überhaupt unterstützt wird. Ich hätte da an die OV2640 (2MP) oder an die OV5640 (5MP) gedacht. Was meinen Sie?

**Comment by tido-** [comment]
Ich habe mich noch mit einem Moderator bei Armbian dazu ausgetauscht. Er meinte es ist eine Frage der erhältlichen Treiber und es gibt viele action-cams die mit [V3 & 8MP Sony Sensor](https://www.youtube.com/watch?v=PIgrToh81Nw) IMX179 laufen, aber ich weiss nicht wie es um die Treiber steht. 

Übrigens bei [spinics ist schon v9](https://www.spinics.net/lists/linux-media/msg130006.html) draussen.

**Comment by tido-** [comment]
Eine gute Frage. 
Eventuell hat der erschaffer von Lichee Pi was in seinen Dateien?
Warst du schon hier: https://www.digi.com/resources/documentation/digidocs/90001546/reference/bsp/cc6/r_mipi.htm 

Und das kennst du wahrscheinlich auch https://groups.google.com/forum/#!searchin/linux-sunxi/v3s%7Csort:date/linux-sunxi/Cu5ldv_SzSc/73FR9h50BAAJ

Macht es Sinn das Design trotzdem auf MIPI CSI auszulegen oder gibt es eine Alternative ?

**Comment by petit-miner** [comment]
Geplant ist ein MIPI CSI FPC Connector der kompatibel mit der Raspberry Pi Kamera ist.
Vielleicht wird ja irgendwann MIPI CSI doch noch unterstützt.

**Comment by tido-** [comment]
Ist der Anschluss für die RPi-Kamera derselbe wie für die OV5640 (5MP) ?

Was ändert sich gemäss dieser Aussage: nicht mehr Raspberry Pi form factor ?

**Comment by petit-miner** [comment]
Auf der Raspberry Pi Kamera wird der OV5647 IC verwendet, welcher über MIPI CSI angesprochen wird.
Auf dem Blueberry Pi wird es eine pinkompatible FPC-Buchse für die Raspberry PI Kamera geben.
Der OV5640 und der OV5647 haben neben einem parallem Port auch eine MIPI CSI Schnittstelle.
Wobei ich auf Ebay und co. die OV5640 nur als parallel finde. Die OV5647 nur als Raspberry Pi Kamera also MIPI CSI.

Also der MIPI CSI Port und der parallel Port (CSI / LCD) sind von einander getrennt.
Ein Raspberry Pi form factor ist mit diesen ganzen Schnittstellen, der Lage der einzelnen Schnittstellen auf einem 2-Layer board nicht zu schaffen. Desweiteren kommt dazu, dass es zu wenig GPIOs gibt um einen 40 Pin GPIO Header möglich zu machen. Unter Hardware/pictures/ habe ich einen Vorentwurf hochgeladen, wo ungefähr welche Schnittstelle sitzt. Da ändert sich wahrscheinlich noch was dran.

**Comment by tido-** [comment]
OV5647 - die muss doch aber einen Treiber für den RPi haben..

Im 2 Lagen Design wird das PCB recht gross, viele Freiflächen, was ist denn der limitierende Faktor(en) statt 3 oder 4 lagig ?
Sind in deinem Design auch noch LED (power, activity) vorgesehen?

Auch wenn der Header nur 28 hat aber in derselben Reihenfolge wie der RPi, so wäre er doch für viele 'Hat' verwendbar. Ein Bild von der Unterseite wäre noch interessant.

**Comment by petit-miner** [comment]
Ja die OV5647 wird von Linux unterstützt, ob MIPI CSI oder auch der Parallele Ausgang unterstützt wird weiß ich nicht. Das übersteigt dann doch mein Wissen.  Ich habe bisher für Kameras irgendwie nur die I²C Treiber gefunden. Wo sind die Treiber für die Kamera selber? Oder gibt es keine weil keine nötig sind, da MIPI CSI Standardisiert ist? 

Power LED und Act LED sind natürlich Pflicht, hatte ich bisher nur noch nicht aufgeschrieben.

Das Problem mit dem Raspberry Pi Layout ist einfach, dass es viele Schnittstellen gibt die dem Raspi nicht entsprechen. z.B statt HDMI gibt es keinen "richtigen" Video Ausgang. 
Die Powerbuchse ist eine Standard DC-Jack. Die 4 Taster für Next previous volume up down usw.
stören ein bisschen im Standard Raspi Layout. Desweiteren müsste man dann schon ein 4-Layer Board nehmen um ein Raspi Layout hinzubekommen. Dazu kommt noch das relativ große Wifi / Bluetooth Modul.
Im Vergleich zum Licheepi zero soll der Blueberrypi alle Interfaces herausführen und somit die volle Funktionalität des V3s bereitstellen.

Oben rechts in der Ecke ist noch relativ viel Platz, da hier noch 3 Step down Converter + ein linearer Regler hin muss. 
Nachdem 6 April habe ich wieder richtig Zeit um aktiv an diesem Projekt zu arbeiten. Ich stecke momentan voll in der Klausurenphase.

Um euer kleines Ratespiel aufzulösen: Nein ich bin nicht aus der Schweiz, komme aus Deutschland. :D

**Comment by tido-** [comment]
> z.B statt HDMI gibt es keinen "richtigen" Video Ausgang.

Was meinst du damit, kein HDMI ?

gc2035 - https://github.com/avafinger/gc2035 

OV5640 - https://github.com/avafinger/ov5640

I have managed to build FFmpeg with Cedrus on Armbian and it seems working.
To grab video stream from the CMOS camera:
`sudo ./ffmpeg -f v4l2 -channel 0 -video_size 640x480 -i /dev/video0 -pix_fmt nv12 -r 30 -b:v 64k -c:v cedrus264 test.mp4`
https://forum.armbian.com/topic/1842-ffmpeg-with-cedrus-h264-hw-encoder-h3-cmos-camera/

Raspi Layout:

- Standard DC-Jack - ist ja auch sinnvoll
- Die 4 Taster für Next previous volume up down - braucht wahrscheinlich auch nicht jeder aber schön sind die da.
- Wifi / Bluetooth Modul - möchtest du noch eines integrieren, via USB? Welches?

Der Vorteil an dem Layout liegt auf der Hand, Gehäuse und anderes sind schon vorhanden und können bei Bedarf angepasst werden.


Dass du aus DE ist war mir bald klar, als ich deinen Link im Forum zu  de.Aliexpress sah :-)

**Comment by petit-miner** [comment]
Bei dem Wlan / Bluetooth Modul habe ich an das RTL8723bs gedacht. Wird über den SDIO Bus angeschlossen + Uart Port. 
Ich habe mir das ganze nochmal angesehen und vielleicht kann man ja auf die 3 USB Ports vom Raspi verzichten und dort dann die Taster und das Mikro unterbringen? 
Ein 4 Layer Pcb kostest ja in China auch nicht mehr die Welt. Bei Jlc Pcb gibt es ein 4-Layer Pcb 10cm*10cm Leadfree und in Blau für 36€. Versand ist kostenlos.

Der V3s hat keinen HDMI Ausgang, man bräuchte einen extra IC um das zu realisieren.  
Vor allem im Bereich der Kamera sind noch viele Fragen offen, z.B. fehlt im aktuellem Treiber die Möglichkeit einen Pin als Clock driver Pin zu definieren um die Kamera ans laufen zu bekommen.
Desweiteren fehlen hier und da Infos die einen in der Entwicklung stoppen.

**Comment by tido-** [comment]
> RTL8723bs

Der V3s hat "Integrated an internal 10/100M PHY" sprich Netzwerk ist vorhanden, dann habe ich mir überlegt, wozu noch WiFi, warum nicht Zigbee?

> 3 USB Ports

Wolltest du das via USB-Hub lösen, ich sehe nur den USB-OTG?
Wenn USB nicht direkt am SoC angebunden ist, wird USB-Attached-SCSI nicht möglich sein. Na ja, 100Mbit vom Ethernet wären auch nur 6MB/s und das schafft fast jedes USB2.0 ohne UAS und die 5MP Kamera liefert wahrscheinlich auch nicht mehr. Es gibt auch einzelne aufrechtstehende USB-A Buchsen.

keinen HDMI Ausgang - dafür Support RGB interface with DE/SYNC mode, up to 1024x768@60fps 

> 4-Layer Pcb 10cm*10cm Leadfree und in Blau für 36€.

Das wäre für 10 Stück, hat es keine SMD Komponenten, sonst braucht es noch die SMD-Stencil zum aufbringen der Lötpaste.
Ich frage mich gerade was die Produktion in Ostdeutschland kosten würde.

**Comment by tido-** [comment]
Ging mit der Klausur alles gut?

Was hälst du davon..
> warum nicht Zigbee?

**Comment by petit-miner** [comment]
Ich hoffe mal 😀 
Der Schaltplan ist jetzt soweit fertig und es fehlen noch ein paar Sachen wie der DC DC Wandler und der Lipo Lade IC. 

Problematisch wird es mit dem Platz auf der Platine. Der SoC vom Raspberry ist ebenhalt wesentlich kleiner als der V3s im TQFP. Zudem fehlt momentan der DC DC Wandler und alle dazugehörigen Bauteile. Vielleicht fällt mir noch was ein, wie ich dass ganze noch lösen kann.
Ich denke einen direkten Zigbee Sockel auf der Platine in den jetzigen Maßen wird nicht möglich sein.
