### ISSUE TITLE
fatal: repository 'https://github.com/petit-miner/linux.git/' not found

### ISSUE THREAD

**Issue by KaDw** [petit-miner/Blueberry-PI#10]
Linux kernel repo seems to be unavailable, I tried neweset kernel but the blueberry won't boot.

**Comment by petit-miner** [comment]
Yes I deleted it, because it is now outdated and the mainline version has all features of the V3s covered.
Which defconfig file are you using? Try using the sunxi_defconfig it should work fine. If you can't even see uboot than you might have a deeper issue and should adress that first.

**Comment by KaDw** [comment]
I got it, it works with U-Boot 2021.01 and 5.10 kernel. I used buildroot to build all components and there was a problem with outdated U-Boot
