### ISSUE TITLE
2-sides pcb + lvds + axp203

### ISSUE THREAD

**Issue by bhgv** [petit-miner/Blueberry-PI#3]
hi,

i did a fork of your blueberry pi, but added LVDS serialiser (SN65LVDS84) with the regular LVDS pin-header, TSC2003 - touch controller, w25q128 - flash, AXP203 power chip instead of EA3036.

https://github.com/bhgv/Blueberry-PI_Allwinner-V3s_LVDS_AXP203

and traced them as 2-sides PCBs.

https://github.com/bhgv/Blueberry-PI_Allwinner-V3s_LVDS_AXP203/tree/master/Hardware/PCB/routed

maybe you interested

**Comment by petit-miner** [comment]
thank you

**Comment by KaDw** [comment]
@bhgv Did you managed to get it up and running with AXP203?

**Comment by bhgv** [comment]
@KaDw 
> Did you managed to get it up and running with AXP203?
not yet. i'm playing now with a ea3036 one. only received PCBs and soldered it partly. too tight contacts on the ea3036 (and AXP203). i think using lm1117 will be better for this chip/board.

**Comment by bhgv** [comment]
@KaDw 
..and on my board wrong connection of the micro-usb. they are mirrored. use full size USB.

**Comment by petit-miner** [comment]
@bhgv this issue is resolved with the new version of the PCB

**Comment by ma6254** [comment]
@bhgv i cannot set the default output voltage
in the AXP203 datasheet：
> As for more details, please refer to “Default Configuration Instruction”.

Do you have this, can you post it?

Thx
