### ISSUE TITLE
Blueberry Pi.pro file was not uploaded.

### ISSUE THREAD

**Issue by searchmawnag** [petit-miner/Blueberry-PI#4]
Please upload Blueberry-PI/Hardware/PCB/Blueberry Pi.pro file.

**Comment by petit-miner** [comment]
Hi searchmawnag,
I'm currently working on a new PCB revison, so I will upload the .pro file if I'm ready with the new PCB revision.

**Comment by petit-miner** [comment]
Hi searchmawnag,
sorry that I'm answering your question so late. Why do you need the .pro file? It is only needed to indicate that a folder is an Eagle project folder. You can open the .sch and .brd files without the .pro file.
