### ISSUE TITLE
repository 'https://github.com/petit-miner/u-boot.git/' not found

### ISSUE THREAD

**Issue by ciprian288** [petit-miner/Blueberry-PI#5]
repository 'https://github.com/petit-miner/u-boot.git/' not found

**Comment by Thore-Krug** [comment]
The V3s SOC is generally supported by Mainline Uboot by now i dont have a Board to test it but support can be tested relatively easily.

**Comment by Thore-Krug** [comment]
You can use Mainline Uboot for the BlueberryPi with the `LicheePi_Zero_defconfig` and the `sunxi` defconfig for mainline Linux Kernel with the `sun8i-v3s-licheepi-zero.dtb` Devicetree according to http://linux-sunxi.org/Blueberry_PI
