### ISSUE TITLE
Distributor for Allwinner V3S 

### ISSUE THREAD

**Issue by NilsMinor** [petit-miner/Blueberry-PI#7]
Hello Blueberry Team,

First of all thanks for sharing your experience designing a RPI module alternative. I was looking for a distributor for Allwinner V3S SoC in Germnay / Europe. Maybe you can help me with a contact. Where did you buy the SoC ?

Thanks,
Nils

**Comment by petit-miner** [comment]
Hallo Nils,
Für einzelne Prototypen habe ich den V3s auf Aliexpress gekauft. Für eine Serienproduktion hätte ich einen Kontakt zu einem Händler in China.

Gruß Marcel

**Comment by NilsMinor** [comment]
Hi Marcel,

danke für dein Feedback :). Kannst du einen Kontakt zum Händler herstellen? Wir überlegen ein SoM zu bauen und sind noch auf der Suche nach einem günstigen Prozessor. Gerne kannst du mir auch eine Mail an nils@electronic-fellows.de schreiben.

Beste Grüße,
Nils
