### ISSUE TITLE
FEL Mode Pin 

### ISSUE THREAD

**Issue by Thore-Krug** [petit-miner/Blueberry-PI#9]
I was interested in creating a Board based on the Allwinner V3s as well and was looking through the documentation of the V3s looking for the Pin initiating the FEL mode. Normally the Pin gets pulled down to Ground which initiates the FEL mode, even though the documentation mentions it briefly its not completely clear which pin on the package it is.

Have i overlooked it in the schematic? Or is the Blueberry Pi not making use of this feature? 

Signed off by: Thore Krug opensource[at]thorekrug.de

**Comment by petit-miner** [comment]
In the lichee pi zero schematics it seems like to be the SPI MISO (Master In Slave Out) Pin. However it makes sense since the Slave can't talk with the Master (V3s)

**Comment by tomwimmenhove** [comment]
Simply shorting out the SPI Flash chip's output seems like a bad idea. The datasheet mentions a "BSP" pin in the boot-configuration flow chars, but this pin is not named anywere else (as in, not listed in the pinout of the chip)

**Comment by petit-miner** [comment]
Yes, you should do it with a pulldown resistor. But the BSP Pin isn't really needed since the V3s prefers booting from an SD Card and you can also always enter FEL Mode through the uboot console.
